apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: Matthew Wilson <matthew.wilson@uk.ibm.com>
    commit.image.appsody.dev/committer: Matthew Wilson <matthew.wilson@uk.ibm.com>
    commit.image.appsody.dev/date: Wed Feb 19 11:26:12 2020 +0000
    commit.image.appsody.dev/message: Populate barista-http path env var from secret
    image.opencontainers.org/created: "2020-02-19T13:46:33Z"
    image.opencontainers.org/documentation: https://github.ibm.com/appsody-coffeeshop/coffeeshop-service
    image.opencontainers.org/revision: e68a957a9ec9ce36c2c6aa7faf27d55f0d3e67dd-modified
    image.opencontainers.org/source: https://github.ibm.com/appsody-coffeeshop/coffeeshop-service/tree/master
    image.opencontainers.org/url: https://github.ibm.com/appsody-coffeeshop/coffeeshop-service
    stack.appsody.dev/authors: Mike Andrasak <andrasak@us.ibm.com>, Andy Mauer <ajmauer@us.ibm.com>,
      Scott Kurz <skurz@us.ibm.com>, Adam Wisniewski <awisniew@us.ibm.com>
    stack.appsody.dev/configured: docker.io/appsody/java-openliberty:0.1
    stack.appsody.dev/created: "2020-02-07T16:20:59Z"
    stack.appsody.dev/description: Open Liberty & OpenJ9 using Maven
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/tag: docker.io/appsody/java-openliberty:0.1.7
    stack.appsody.dev/title: Open Liberty
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: coffeeshop-service-appsody
    stack.appsody.dev/id: java-openliberty
    stack.appsody.dev/version: 0.1.7
  name: coffeeshop-service-appsody
  namespace: default
spec:
  applicationImage: matthewpwilson/coffeeshop-service-appsody:wed4
  createKnativeService: false
  env:
  - name: MP_MESSAGING_CONNECTOR_LIBERTY_KAFKA_BOOTSTRAP_SERVERS
    value: my-cluster-kafka-bootstrap.kafka.svc:9092
  - name: COM_IBM_RUNTIMES_EVENTS_COFFEESHOP_HTTP_BARISTASERVICE_MP_REST_URL
    valueFrom:
      secretKeyRef:
        key: url
        name: appsody-http-appsody-http
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 10
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 10
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/scrape: "true"
    consumes:
    - category: openapi
      name: appsody-http
      namespace: appsody-http
    port: 9080
    type: NodePort
  stack: java-openliberty
  version: 1.0.0
status: {}
